#! /bin/sh
bspc rule -r "*"

# Autostart.
killall sxhkd
sxhkd &
unclutter &
feh --no-fehbg --bg-center ~/wp/cityscape.jpg.webp
$HOME/.config/polybar/launch.sh

# Monitors.
bspc monitor -d 1 2 3 IV V VI VII 

#Colors
bspc config normal_border_color		"#fbf1c7"
bspc config active_border_color 	"#f4bc87"
bspc config focused_border_color 	"#d79921"
bspc config presel_feedback_color 	"#7c6f64"

# Configuration
bspc config border_width         2
bspc config window_gap           3 
bspc config top_padding 	 22
bspc config right_padding	 0
bspc config bottom_padding	 0
bspc config left_padding	 0
bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gappless_monocle	 true 
bspc config focus_follows_pointer true

bspc config initial_polarity second_child

# Rules
bspc rule -a firefox desktop=^2
