#! /bin/sh

# SOME EXEC
# Return: Terminal, d: Run program, Escape: Reload sxhkd
super + {Return,d,Escape}
	{urxvt,dmenu_run -fn "iosevka-regular" -nb '#32302f' -nf '#ebdbb2' -sb '#8f3f71' -sf '#ebdbb2' ,pkill -USR1 -x sxhkd}

### SYSTEM HOTKEYS ###
# Restart/Shutdown computer
super + {F12,F11}
	confirmaction.sh {"Are you sure you want to shut down?" "shutdown now","Are you sure you want to reboot?" "reboot"}

### BSPWM HOTKEYS ###
# Quit/Restart bspwm
super + {F1, alt + r}
	{confirmaction.sh "Are you sure you want to quit bspwm?" "bspc quit",bspc wm -r}

# Close or kill
super + {_,shift + }w
	bspc node -{c,k}

# Alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# Send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

### WINDOW MANIPULATION ###
#Resizing
super + alt + {h,j,k,l}
	bspwm_resize {west,south,north,east} 50

# Set the window state
super + {t,shift + t,space,f}
	bspc node -t "~{tiled,pseudo_tiled,floating,fullscreen}"

# Set the node flags
super + ctrl + {m,l,s,p}
	bspc node -g {marked,locked,sticky,private}

### FOCUS AND SWAP ###
# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# Focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# Focus the next/previous node in the current desktop
alt + {_,shift + } Tab
	bspc node -f {next,prev}.local

# Focus the last node
alt + grave
	bspc node -f last

# Focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# Focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# PRESELECTION
# Preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p "~{west,south,north,east}"

# Preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# Move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}
